### PR TITLE
Type insanity

### PR DESCRIPTION
**Pull request by benweitzman**

### CODE REVIEW

**Comment by mightybyte** [comment]
Wow.  Is this strictly necessary?  :)  I'm usually hesitant about this kind of thing on the basis of maintainability.  I'm not opposed to considering it, but I would like to understand what problem it solves.

**Comment by benweitzman** [comment]
I'm not totally sure. So the way that the we'll be writing instances of `ToJSON` for different versions is something like 

```
data Object = ..
instance (Tagged V1 Object) where
  toJSON (Tagged (Object ..)) = object [..]

instance (Tagged V2 Object) where
  toJSON (Tagged (Object ..)) = object [..]
```

And then to bring all of the different versions together, you would write something like

```
instance SerializedVersion Object where
  serializers = M.fromList [(v1, getSerializer pv1), (v2, getSerializer pv2)]
```

where `v1` is the data equivalent of the `V1` type and `pv1`is `Proxy :: Proxy V1`. 

There are two annoying things about this: 
1. You have to keep track of all these different representations of versions across the data/type boundary
2. There's some unnecessary repetition of the version in the definition, so you could end up associating the V1 version with the V2 serializer. 

This branch addresses both of these so that you only need to write

```
instance SerializedVersion Object where
   type SerializerVersions Object = '[V1, V2]
```

which is IMO much cleaner.

Unfortunately it means that we have to jump through some type hoops to make sure that you can't associate a version with an object without a `ToJSON` instance for that version. In the current way of doing things, that would be impossible since `getSerializer pv1` is a concrete term and forces the type checker to do the verification. But I believe all of the craziness in here would be opaque to any code that uses this library. 

So yeah, don't know if it's strictly necessary but it was something that was bugging me about the current implementation.

**Comment by mightybyte** [comment]
Ok, that seems reasonable to me.  Could you maybe put some of this higher level explanation in the comments in a way that connects it to specific parts of the code?

Also, this discussion brought one other question to mind.  Your example above assumes that we are defining two different version representations for one type.  How would your system work if the different versions were different types?  For example:

```
data Foo_V1 = Foo_V1
    { fooAlpha :: Int
    , fooBeta  :: String
    , fooGamma :: String
    }

data Foo_V2 = Foo_V2
    { fooAlpha :: Int
    , fooGamma :: FooType
    }
```

**Comment by benweitzman** [comment]
One of the goals for this project is to make sure there's no need to have data be represented by two different types. All versioning happens at the serialization/deserialization level, not at the logic level. Not sure if you're using `Foo_V1` and `Foo_V2` in the sense that they'd be existing at the same time or just for making it easier to talk about the "same" datatype at different snapshots in time. Assuming the latter.

The first instance we would write would be for `V1` of `Foo_V1` (side note, if there is only one version, then you don't need to write a `Tagged` instance). 

``` haskell
instance ToJSON (Tagged V1 Foo_V1) where
  toJSON (Tagged (Foo_V1 alpha beta gamma)) = object [ "alpha" .= alpha
                                                     , "beta" .= beta
                                                     , "gamma" .= gamma
                                                     ]
```

Now we decide that beta should be removed and gamma should morph to a more complex type. However we still need to support `V1`, so we can't remove beta from `Foo_V2`. For gamma, we have two options:
1. add a "gammaComplex" field in addition to the simple field and have the V1 serializer use one and the V2 serialize use the other
   
   ``` haskell
   data Foo_V2 = Foo_V2
       { fooAlpha :: Int
       , fooBeta :: String -- note this has to be included
       , fooGammaSimple :: String
       , fooGammaComplex :: FooType
       }
   
   instance ToJSON (Tagged V1 Foo_V2) where
     toJSON (Tagged (Foo_V1 alpha beta gamma _)) = object [ "alpha" .= alpha
                                                          , "beta" .= beta
                                                          , "gamma" .= gamma -- simple
                                                          ]
   
   instance ToJSON (Tagged V2 Foo_V2) where
     toJSON (Tagged (Foo_V1 alpha _  _ gamma)) = object [ "alpha" .= alpha
                                                        -- no beta
                                                        , "gamma" .= gamma -- complex
                                                        ]
   ```
2. change gamma from `String` to `FooType` and write a function of type `FooType -> String` which is used to transform the complex version to the simple version
   
   ``` haskell
   data Foo_V2 = Foo_V2
       { fooAlpha :: Int
       , fooBeta :: String
       , fooGamma :: FooType
       }
   
   simplifyGamma :: FooType -> String
   simplifyGamma complex = ...
   
   instance ToJSON (Tagged V1 Foo_V2) where
     toJSON (Tagged (Foo_V1 alpha beta gamma)) = object [ "alpha" .= alpha
                                                        , "beta" .= beta
                                                        , "gamma" .= simplifyGamma gamma
                                                        ]
   
   instance ToJSON (Tagged V2 Foo_V2) where
     toJSON (Tagged (Foo_V1 alpha _ gamma)) = object [ "alpha" .= alpha
                                                     -- no beta
                                                     , "gamma" .= gamma
                                                     ]
   ```

Then after we have most people upgraded and/or decide to stop supporting V1, we can drop the unnecessary stuff from the data definition, so it would look similar to your `Foo_V2`. 

I'm not 100% sure which of the approaches would be better, but I'm inclined to side with 2

**Comment by mightybyte** [comment]
> One of the goals for this project is to make sure there's no need to have data be represented by two different types. All versioning happens at the serialization/deserialization level, not at the logic level.

Ok, this sounds good.

I was thinking for a moment that this goal is impossible, and that you have to be willing to have two separate types at the same time in order to be able to support backwards-incompatible changes.  (Although I've actually used the two-type approach in production and it is admittedly miserable to work with.)  But I guess the strategy you describe of keeping the superset (using either of your two options) in the type until enough time passes seems like it should work.

I agree that option #2 is probably more desirable.  But it seems like there could conceivably be situations where it's impossible to write `FooType -> String` (for instance if FooType doesn't contain enough information).  In those cases it seems like falling back to option #1 should be fine.

**Pull request merged**
